
name: Dev CI CD pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  determine_runner:
    name: Determine the Runner
    runs-on: ubuntu-latest
    outputs:
      runner_label: ${{ steps.set_runner.outputs.runner_label }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine Runner from Actor
        id: set_runner
        run: |
          RUNNER_LABEL="default-runner"
          ACTOR="test"
          echo "Triggered by actor: $ACTOR"
          if [ -f .github/runner-mapping.json ]; then
            RUNNER_LABEL=$(jq -r --arg ACTOR "$ACTOR" '.[$ACTOR] // "default-runner"' .github/runner-mapping.json)
          else
            echo "Runner mapping configuration file not found. Using default."
          fi
          echo "Assigned Runner Label: $RUNNER_LABEL"
          echo "::set-output name=runner_label::$RUNNER_LABEL"
  checkout_code:
    name: Checkout Repository Code
    needs: determine_runner
    runs-on: ${{ needs.determine_runner.outputs.runner_label }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}  
          fetch-depth: 0

  check_code_changes:
    name: Check Code Changes
    needs: [determine_runner, checkout_code]
    runs-on: ${{ needs.determine_runner.outputs.runner_label }}
    outputs:
      backend_changed: ${{ steps.check.outputs.backend_changed }}
      ui_changed: ${{ steps.check.outputs.ui_changed }}
      emailservice_changed: ${{ steps.check.outputs.emailservice_changed }}
      monitoring_changed: ${{steps.check.outputs.monitoring_changed}}
      dashboardui_changed: ${{steps.check.outputs.dashboardui_changed}}
    steps:
      - name: Check for relevant updates
        id: check
        run: |
          $BACKEND_CHANGED = $false
          $UI_CHANGED = $false
          $EMAILSERVICE_CHANGED = $false
          $MONITORING_CHANGED = $false
          $DASHBOARDUI_CHANGED = $false
          #  Check ITPPBackend Code
          if (git rev-parse --verify HEAD~1 2>$null) {
            if (git diff --name-only HEAD~1 HEAD | Select-String '^ITPPBackend/') {
              $BACKEND_CHANGED = $true
            }
          } else {
            if (git ls-files --others --exclude-standard | Select-String '^ITPPBackend/') {
              $BACKEND_CHANGED = $true
            }
          }
          # Check ITPPUI code
          if (git rev-parse --verify HEAD~1 2>$null) {
            if (git diff --name-only HEAD~1 HEAD | Select-String '^ITPPUI/') {
              $UI_CHANGED = $true
            }
          } else {
            if (git ls-files --others --exclude-standard | Select-String '^ITPPUI/') {
              $UI_CHANGED = $true
            }
          }
          # Check EmailNotificationService Code
          if (git rev-parse --verify HEAD~1 2>$null) {
            if (git diff --name-only HEAD~1 HEAD | Select-String '^EmailNotificationService/') {
              $EMAILSERVICE_CHANGED = $true
            }
          } else {
            if (git ls-files --others --exclude-standard | Select-String '^EmailNotificationService/') {
              $EMAILSERVICE_CHANGED = $true
            }
          }
          # CHECK MONIORING BACKEND CODE
          if (git rev-parse --verify HEAD~1 2>$null) {
            if (git diff --name-only HEAD~1 HEAD | Select-String '^MonitoringDashboardBackend/') {
              $MONITORING_CHANGED = $true
            }
          } else {
            if (git ls-files --others --exclude-standard | Select-String '^MonitoringDashboardBackend/') {
              $MONITORING_CHANGED = $true
            }
          }
          # CHECK MONITORING DASHBOARD UI CODE
          if (git rev-parse --verify HEAD~1 2>$null) {
            if (git diff --name-only HEAD~1 HEAD | Select-String '^MonitoringDashboardUI/') {
              $DASHBOARDUI_CHANGED = $true
            }
          } else {
            if (git ls-files --others --exclude-standard | Select-String '^MonitoringDashboardUI/') {
              $DASHBOARDUI_CHANGED = $true
            }
          }
          echo "Backend Changed: $BACKEND_CHANGED"
          echo "UI Changed: $UI_CHANGED"
          echo "Email Service Changed: $EMAILSERVICE_CHANGED"
          echo "::set-output name=backend_changed::$BACKEND_CHANGED"
          echo "::set-output name=ui_changed::$UI_CHANGED"
          echo "::set-output name=emailservice_changed::$EMAILSERVICE_CHANGED"
          echo "::set-output name=monitoring_changed::$MONITORING_CHANGED"
          echo "::set-output name=dashboardui_changed::$DASHBOARDUI_CHANGED"
  check_helm_changes:
    name: Check charts Updates
    needs: [determine_runner, checkout_code]
    runs-on: ${{ needs.determine_runner.outputs.runner_label }}
    outputs:
      helm_itppui_changed: ${{ steps.helm_check.outputs.helm_itppui_changed }}
      helm_itppbackend_changed: ${{ steps.helm_check.outputs.helm_itppbackend_changed }}
      helm_nginx_ingress_changed: ${{ steps.helm_check.outputs.helm_nginx_ingress_changed }}
      helm_monitoring_changed: ${{ steps.helm_check.outputs.helm_monitoring_changed }}
      helm_prometheus_changed: ${{ steps.helm_check.outputs.helm_prometheus_changed }}
      helm_dashboardui_changed: ${{steps.helm_check.outputs.helm_dashboardui_changed}}
      helm_emailservice_changed: ${{steps.helm_check.outputs.helm_emailservice_changed}}
    steps:
      - name: Check charts Changes
        id: helm_check
        run: |
            $HELM_ITPPUI_CHANGED = $false
            $HELM_ITPPBACKEND_CHANGED = $false
            $HELM_NGINX_INGRESS_CHANGED = $false
            $HELM_MONITORING_CHANGED = $false
            $HELM_DASHBOARDUI_CHANGED = $false
            $HELM_PROMETHEUS_CHANGED = $false
  
            if (git rev-parse --verify HEAD~1 2>$null) {
              if (git diff --name-only HEAD~1 HEAD | Select-String '^charts/itppui/') {
                $HELM_ITPPUI_CHANGED = $true
              }
              if (git diff --name-only HEAD~1 HEAD | Select-String '^charts/nginx-ingress/') {
                $HELM_NGINX_INGRESS_CHANGED = $true
              }
              if (git diff --name-only HEAD~1 HEAD | Select-String '^charts/nginx-ingress/') {
                $HELM_NGINX_INGRESS_CHANGED = $true
              }
              if (git diff --name-only HEAD~1 HEAD | Select-String '^charts/monitoringdashboardbackend/') {
                $HELM_MONITORING_CHANGED = $true
              }
              if (git diff --name-only HEAD~1 HEAD | Select-String '^charts/monitoringdashboardui/') {
                $HELM_DASHBOARDUI_CHANGED = $true
              }
              if (git diff --name-only HEAD~1 HEAD | Select-String '^charts/custom-prometheus/') {
                $HELM_PROMETHEUS_CHANGED = $true
              }
            } else {
              if (git ls-files --others --exclude-standard | Select-String '^charts/itppui/') {
                $HELM_ITPPUI_CHANGED = $true
              }
              if (git ls-files --others --exclude-standard | Select-String '^charts/itppbackend/') {
                $HELM_ITPPBACKEND_CHANGED = $true
              }
              if (git ls-files --others --exclude-standard | Select-String '^charts/nginx-ingress/') {
                $HELM_NGINX_INGRESS_CHANGED = $true
              }
              if (git ls-files --others --exclude-standard | Select-String '^charts/monitoringdashboardbackend/') {
                $HELM_MONITORING_CHANGED = $true
              }
              if (git ls-files --others --exclude-standard | Select-String '^charts/monitoringdashboardbackend/') {
                $HELM_DASHBOARDUI_CHANGED  = $true
              }
              if (git ls-files --others --exclude-standard | Select-String '^charts/eamilnotificationservice') {
                $HELM_EMAILSERVICE_CHANGED  = $true
              }
              if (git ls-files --others --exclude-standard | Select-String '^charts/custom-prometheus/') {
                $HELM_PROMETHEUS_CHANGED = $true
              }
            }

            echo "charts ITPPUI Changed: $HELM_ITPPUI_CHANGED"
            echo "charts ITPPBackend Changed: $HELM_ITPPBACKEND_CHANGED"
            echo "charts Nginx-Ingress Changed: $HELM_NGINX_INGRESS_CHANGED"
            echo "charts Monitoring Changed: $HELM_MONITORING_CHANGED"
            echo "charts DashboardUI Changed: $HELM_DASHBOARDUI_CHANGED"
            echo "charts Promethues Changed: $HELM_PROMETHEUS_CHANGED"
    
            echo "::set-output name=helm_itppui_changed::$HELM_ITPPUI_CHANGED"
            echo "::set-output name=helm_itppbackend_changed::$HELM_ITPPBACKEND_CHANGED"
            echo "::set-output name=helm_nginx_ingress_changed::$HELM_NGINX_INGRESS_CHANGED"
            echo "::set-output name=helm_monitoring_changed::$HELM_MONITORING_CHANGED"
            echo "::set-output name=helm_dashboardui_changed::$HELM_DASHBOARDUI_CHANGED"
            echo "::set-output name=helm_emailservice_changed::$HELM_EMAILSERVICE_CHANGED"
            echo "::set-output name=helm_promtheus_changed::$HELM_PROMETHEUS_CHANGED"

  build:
    name: Build Images If Neccessary
    needs: [determine_runner, check_code_changes]
    runs-on: ${{ needs.determine_runner.outputs.runner_label }}

    steps:
      - name: Check Outputs
        run: |
          echo "Backend Changed: ${{ needs.check_code_changes.outputs.backend_changed}}"
          echo "UI Changed: ${{needs.check_code_changes.outputs.ui_changed}}"
          echo "Email Service Changed: ${{needs.check_code_changes.outputs.emailservice_changed}}"
          echo "Monitoring Changed: ${{needs.check_code_changes.outputs.monitoring_changed}}"
          echo "dashboardUI Changed: ${{needs.check_code_changes.outputs.monitoring_changed}}"
          echo "Issue Rag: ${{github.sha}}"
      - name: Checkout Repository
        uses: actions/checkout@v3
  
      - name: Build and push ITPPBackend Docker image
        if: ${{ needs.check_code_changes.outputs.backend_changed == 'True' }}
        run: |
          $TAG="ghcr.io/vincentdevopsresearch/skyworlditpp/itppbackend:latest"
          docker build -f ./ITPPBackend/Dockerfile -t $TAG ./ITPPBackend 
      - name: Build and push ITPPUI Docker image
        if: ${{ needs.check_code_changes.outputs.ui_changed == 'True' }}
        run: |
          $TAG="ghcr.io/vincentdevopsresearch/skyworlditpp/itppui:latest"
          docker build -f ./ITPPUI/Dockerfile -t $TAG ./ITPPUI
      
      - name: Build and push DashboardUI Docker image
        if: ${{ needs.check_code_changes.outputs.dashboardui_changed == 'True' }}
        run: |
            $TAG="ghcr.io/vincentdevopsresearch/monitoringdashboard/dashbaordui:latest"
            docker build -f ./MonitoringDashboardUI/Dockerfile -t $TAG ./MonitoringDashboardUI
      - name: Build and push EmailNotificationService Docker image
        if: ${{ needs.check_code_changes.outputs.emailservice_changed == 'True' }}
        run: |
          $TAG="ghcr.io/vincentdevopsresearch/emailnotificationservice:latest"
          docker build -f ./EmailNotificationService/Dockerfile -t $TAG ./EmailNotificationService
      - name: Build and push MonitoringBackend Docker image
        if: ${{ needs.check_code_changes.outputs.monitoring_changed == 'True' }}
        run: |
          $TAG="ghcr.io/vincentdevopsresearch/monitoringdashboard/dashbaordbackend:latest"
          docker build -f ./MonitoringDashboardBackend/Dockerfile -t $TAG ./MonitoringDashboardBackend
  deploy:
    name: Deploy Artifacts with charts
    needs: [determine_runner, check_code_changes, check_helm_changes, build]
    runs-on: ${{ needs.determine_runner.outputs.runner_label }}

    steps:
      - name: Deploy ITPPBackend with charts
        if: ${{ needs.check_code_changes.outputs.backend_changed == 'True' || needs.check_helm_changes.outputs.helm_itppbackend_changed == 'True' }}
        run: |
          helm uninstall itppbackend
          helm upgrade --install itppbackend ./charts/itppbackend
      - name: Deploy ITPPUI with charts
        if: ${{ needs.check_code_changes.outputs.ui_changed == 'True' || needs.check_helm_changes.outputs.helm_itppui_changed == 'True' }}
        run: |
          helm uninstall itppui
          helm upgrade --install itppui ./charts/itppui
      - name: Deploy DASHBOARDUI with charts
        if: ${{ needs.check_code_changes.outputs.dashboardui_changed == 'True' || needs.check_helm_changes.outputs.helm_dashboardui_changed == 'True' }}
        run: |
          helm uninstall dashboardui
          helm upgrade --install dashboardui ./charts/monitoringdashboardui
      - name: Deploy Monitoring Dashboard Backend with charts
        if: ${{ needs.check_helm_changes.outputs.helm_monitoring_changed == 'True' || needs.check_code_changes.outputs.monitoring_changed == 'True' }}
        run: |
          helm uninstall monitoring-dashboard-backend
          helm upgrade --install monitoring-dashboard-backend ./charts/monitoringdashboardbackend
      - name: Deploy Email Notification Service with charts
        if: ${{needs.check_code_changes.outputs.emailservice_changed == 'True' || needs.check_helm_changes.outputs.helm_emailservice_changed == 'True'}}
        run: |
          helm uninstall email-notification-service
          helm upgare --install email-notification-service ./charts/
      - name: Deploy Nginx-Ingress with charts
        if: ${{ needs.check_helm_changes.outputs.helm_nginx_ingress_changed == 'True' }}
        run: |
          helm uninstall nginx-ingress
          helm upgrade --install nginx-ingress ./charts/nginx-ingress -f  ./charts/nginx-ingress/values-dev.yaml
      - name: Deploy Prometheus with charts
        if: ${{ needs.check_helm_changes.outputs.helm_prometheus_changed == 'True' }}
        run: |
            helm upgrade --install my-promtheus ./charts/custom-promtheus 
      