name: Test CI CD pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  check_code_changes:
    name: Check Code Changes
    runs-on: ubuntu-latest
    outputs:
      backend_changed: ${{ steps.check.outputs.backend_changed }}
      ui_changed: ${{ steps.check.outputs.ui_changed }}
      emailservice_changed: ${{ steps.check.outputs.emailservice_changed }}
      monitoring_changed: ${{steps.check.outputs.monitoring_changed}}
      dashboardui_changed: ${{steps.check.outputs.dashboardui_changed}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for relevant updates
        id: check
        run: |
          BACKEND_CHANGED=false
          UI_CHANGED=false
          EMAILSERVICE_CHANGED=false
          MONITORING_CHANGED=false
          DASHBOARDUI_CHANGED=false
          
          if git rev-parse --verify HEAD~1 > /dev/null 2>&1; then
            if git diff --name-only HEAD~1 HEAD | grep '^ITPPBackend/'; then
              BACKEND_CHANGED=true
            fi
            if git diff --name-only HEAD~1 HEAD | grep '^ITPPUI/'; then
              UI_CHANGED=true
            fi
            if git diff --name-only HEAD~1 HEAD | grep '^EmailNotificationService/'; then
              EMAILSERVICE_CHANGED=true
            fi
            if git diff --name-only HEAD~1 HEAD | grep '^MonitoringDashboardBackend/'; then
              MONITORING_CHANGED=true
            fi
            if git diff --name-only HEAD~1 HEAD | grep '^MonitoringDashboardUI/'; then
              DASHBOARDUI_CHANGED=true
            fi
          else
            if git ls-files --others --exclude-standard | grep '^ITPPBackend/'; then
              BACKEND_CHANGED=true
            fi
            if git ls-files --others --exclude-standard | grep '^ITPPUI/'; then
              UI_CHANGED=true
            fi
            if git ls-files --others --exclude-standard | grep '^EmailNotificationService/'; then
              EMAILSERVICE_CHANGED=true
            fi
            if git ls-files --others --exclude-standard | grep '^MonitoringDashboardBackend/'; then
              MONITORING_CHANGED=true
            fi
            if git ls-files --others --exclude-standard | grep '^MonitoringDashboardUI/'; then
              DASHBOARDUI_CHANGED=true
            fi
          fi

          echo "::set-output name=backend_changed::$BACKEND_CHANGED"
          echo "::set-output name=ui_changed::$UI_CHANGED"
          echo "::set-output name=emailservice_changed::$EMAILSERVICE_CHANGED"
          echo "::set-output name=monitoring_changed::$MONITORING_CHANGED"
          echo "::set-output name=mdashboardui_changed::$DASHBOARDUI_CHANGED"

  check_helm_changes:
    name: Check charts Changes
    runs-on: ubuntu-latest
    outputs:
      helm_itppui_changed: ${{ steps.helm_check.outputs.helm_itppui_changed }}
      helm_itppbackend_changed: ${{ steps.helm_check.outputs.helm_itppbackend_changed }}
      helm_nginx_ingress_changed: ${{ steps.helm_check.outputs.helm_nginx_ingress_changed }}
      helm_monitoring_changed: ${{ steps.helm_check.outputs.helm_monitoring_changed }}
      helm_promtehus_changed: ${{steps.helm_check.outputs.helm_prometheus_changed}}
      helm_dashboardui_changed: ${{steps.helm_check.outputs.helm_dashboardui_changed}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check charts Changes
        id: helm_check
        run: |
          HELM_ITPPUI_CHANGED=false
          HELM_ITPPBACKEND_CHANGED=false
          HELM_NGINX_INGRESS_CHANGED=false
          HELM_MONITORING_CHANGED=false
          HELM_DASHBOARDUI_CHANGED=false
          HELM_PROMETHEUS_CHANGED=false

          if git rev-parse --verify HEAD~1 > /dev/null 2>&1; then
            if git diff --name-only HEAD~1 HEAD | grep '^charts/itppui/'; then
              HELM_ITPPUI_CHANGED=true
            fi
            if git diff --name-only HEAD~1 HEAD | grep '^charts/itppbackend/'; then
              HELM_ITPPBACKEND_CHANGED=true
            fi
            if git diff --name-only HEAD~1 HEAD | grep '^charts/nginx-ingress/'; then
              HELM_NGINX_INGRESS_CHANGED=true
            fi
            if git diff --name-only HEAD~1 HEAD | grep '^charts/monitoringdashboardbackend/'; then
              HELM_MONITORING_CHANGED=true
            fi
            if git diff --name-only HEAD~1 HEAD | grep '^charts/monitoringdashboardui/'; then
              HELM_DASHBOARDUI_CHANGED=true
            fi
            if git diff --name-only HEAD~1 HEAD | grep '^charts/custom-prometheus/'; then
              HELM_PROMETHEUS_CHANGED=true
            fi
          else
            if git ls-files --others --exclude-standard | grep '^charts/itppui/'; then
              HELM_ITPPUI_CHANGED=true
            fi
            if git ls-files --others --exclude-standard | grep '^charts/itppbackend/'; then
              HELM_ITPPBACKEND_CHANGED=true
            fi
            if git ls-files --others --exclude-standard | grep '^charts/nginx-ingress/'; then
              HELM_NGINX_INGRESS_CHANGED=true
            fi
            if git ls-files --others --exclude-standard | grep '^charts/monitoringdashboardui/'; then
              HELM_DASHBOARDUI_CHANGED=true
            fi
            if git ls-files --others --exclude-standard | grep '^charts/monitoringdashboardbackend/'; then
              HELM_MONITORING_CHANGED=true
            fi
            if git ls-files --others --exclude-standard | grep '^charts/custom-prometheus/'; then
              HELM_PROMETHEUS_CHANGED=true
            fi
          fi

          echo "::set-output name=helm_itppui_changed::$HELM_ITPPUI_CHANGED"
          echo "::set-output name=helm_itppbackend_changed::$HELM_ITPPBACKEND_CHANGED"
          echo "::set-output name=helm_nginx_ingress_changed::$HELM_NGINX_INGRESS_CHANGED"
          echo "::set-output name=helm_dashboardui_changed::$HELM_DASHBOARDUI_CHANGED"
          echo "::set-output name=helm_monitoring_changed::$HELM_MONITORING_CHANGED"
          echo "::set-output name=helm_promtheus_changed::$HELM_PROMETHEUS_CHANGED"

  build:
    name: Build Docker Images
    needs: [check_code_changes]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build and push ITPPBackend Docker image
        if: ${{ needs.check_code_changes.outputs.backend_changed == 'true' }}
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          TAG="ghcr.io/$REPO_NAME/itppbackend:${{ github.sha }}"
          docker buildx build -f ./ITPPBackend/Dockerfile -t $TAG ./ITPPBackend --push

      - name: Build and push ITPPUI Docker image
        if: ${{ needs.check_code_changes.outputs.ui_changed == 'true' }}
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          TAG="ghcr.io/$REPO_NAME/itppui:${{ github.sha }}"
          docker buildx build -f ./ITPPUI/Dockerfile -t $TAG ./ITPPUI --push

      - name: Build and push DASHBOARD Docker image
        if: ${{ needs.check_code_changes.outputs.dashboardui_changed == 'true' }}
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          TAG="ghcr.io/$REPO_NAME/monitoringdashboardui:${{ github.sha }}"
          docker buildx build -f ./MonitoringDashboardUI/Dockerfile -t $TAG ./MonitoringDashboardUI --push

      - name: Build and push Monitoringbackend Docker image
        if: ${{ needs.check_code_changes.outputs.monitoring_changed == 'true' }}
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          TAG="ghcr.io/$REPO_NAME/monitoringdashboardbackend:${{ github.sha }}"
          docker buildx build -f ./MonitoringDashboardBackend/Dockerfile -t $TAG ./MonitoringDashboardBackend --push

      - name: Build and push EmailNotificationService Docker image
        if: ${{ needs.check_code_changes.outputs.emailservice_changed == 'true' }}
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          TAG="ghcr.io/$REPO_NAME/emailnotificationservice:${{ github.sha }}"
          docker buildx build  -f ./EmailNotificationService/Dockerfile -t $TAG ./EmailNotificationService --push

          - name: Build and push MonitoringDashboardBackend Docker image
          if: ${{ needs.check_code_changes.outputs.monitoring_changed== 'true' }}
          run: |
            REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
            TAG="ghcr.io/$REPO_NAME/monitoringdashboardbackend:${{ github.sha }}"
            docker buildx build  -f ./MonitoringDashboardBackend/Dockerfile -t $TAG ./MonitoringDashboardBackend --push
        
  deploy:
    name: Deploy Artifacts with charts
    needs: [check_code_changes, check_helm_changes, build]
    runs-on: Linux
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy ITPPBackend with charts
        if: ${{ needs.check_code_changes.outputs.backend_changed == 'true' || needs.check_helm_changes.outputs.helm_itppbackend_changed == 'true' }}
        run: |
          helm upgrade --install itppbackend ./charts/itppbackend --set image.tag=${{ github.sha }}

      - name: Deploy ITPPUI with charts
        if: ${{ needs.check_code_changes.outputs.ui_changed == 'true' || needs.check_helm_changes.outputs.helm_itppui_changed == 'true' }}
        run: |
          helm upgrade --install itppui ./charts/itppui --set image.tag=${{ github.sha }}
    
      - name: Deploy DASHBOARDUI with charts
        if: ${{ needs.check_code_changes.outputs.dashboardui_changed == 'True' || needs.check_helm_changes.outputs.helm_dashboardui_changed == 'True' }}
        run: |
          helm uninstall dashboardui
          helm upgrade --install dashboardui ./charts/monitoringdashboardui --set image.tag=${{ github.sha }}
  
      - name: Deploy Monitoring Dashboard Backend with charts
        if: ${{ needs.check_helm_changes.outputs.helm_monitoring_changed == 'True' || needs.check_code_changes.outputs.monitoring_changed == 'True' }}
        run: |
          helm uninstall monitoring-dashboard-backend
          helm upgrade --install monitoring-dashboard-backend ./charts/monitoringdashboardbackend --set image.tag=${{ github.sha }}
      
      - name: Deploy Nginx-Ingress with charts
        if: ${{ needs.check_helm_changes.outputs.helm_nginx_ingress_changed == 'true' }}
        run: |
          helm uninstall nginx-ingress
          helm upgrade --install nginx-ingress ./charts/nginx-ingress

      - name: Deploy Monitoring Backend with charts
        if: ${{ needs.check_helm_changes.outputs.helm_monitoring_changed == 'true' }}
        run: |
          helm upgrade --install  monitoring-dashboard-backend ./charts/monitoringdashboardbackend

      - name: Deploy Nginx-Ingress with charts
        if: ${{ needs.check_helm_changes.outputs.helm_promtehus_changed == 'True' }}
        run: |
            helm upgrade --install my-promtheus ./charts/custom-promtheus 

      - name: Deploy Monitoring Backend with charts
        if: ${{ needs.check_helm_changes.outputs.helm_monitoring_changed == 'true' }}
        run: |
          helm upgrade --install  monitoring-dashboard-backend ./charts/monitoringdashboardbackend
          
      - name: Deploy Prometheus with charts
        if: ${{ needs.check_helm_changes.outputs.helm_promtehus_changed == 'True' }}
        run: |
            helm upgrade --install my-promtheus ./charts/custom-promtheus